language: node_js

script: yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  fqdn: "https://mracos.me"
  target-branch: master
  on:
    branch: develop
