language: node_js
node_js:
  - "9.8.0"

env:
  - NODE_ENV=production YARN_PRODUCTION=false

script: yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: dist
  target-branch: master
  on:
    branch: develop
